### ISSUE TITLE
Incompatible dependencies within shadergradient and with other packages

### ISSUE THREAD

**Issue by AthenaKam** [ruucm/shadergradient#92]
When I install shadergradient this is the error message I get

```npm warn ERESOLVE overriding peer dependency
npm verbose attempt to log crashed ERESOLVE overriding peer dependency {
npm verbose   code: 'ERESOLVE',
npm verbose   edge: {
npm verbose     type: 'peer',
npm verbose     name: 'three',
npm verbose     spec: '>= 0.159.0',
npm verbose     error: 'INVALID',
npm verbose     from: {
npm verbose       name: '@monogrid/gainmap-js',
npm verbose       version: '3.0.5',
npm verbose       location: 'node_modules/@react-three/drei/node_modules/@monogrid/gainmap-js',
npm verbose       isWorkspace: false,
npm verbose       dependents: [Array]
npm verbose     }
npm verbose   },
npm verbose   dep: {
npm verbose     name: 'three',
npm verbose     version: '0.167.1',
npm verbose     whileInstalling: {
npm verbose       name: '@react-three/drei',
npm verbose       version: '9.109.5',
npm verbose       path: '/Users/athena.kam/Documents/atr/aaam-bot-client/node_modules/@react-three/drei'
npm verbose     },
npm verbose     location: 'node_modules/three',
npm verbose     isWorkspace: false,
npm verbose     dependents: [ [Object] ]
npm verbose   },
npm verbose   force: false,
npm verbose   isMine: false,
npm verbose   strictPeerDeps: false,
npm verbose   current: {
npm verbose     name: 'three',
npm verbose     version: '0.154.0',
npm verbose     location: 'node_modules/three',
npm verbose     isWorkspace: false,
npm verbose     dependents: [ [Object] ]
npm verbose   },
npm verbose   peerConflict: {
npm verbose     name: 'three',
npm verbose     version: '0.154.0',
npm verbose     location: 'node_modules/three',
npm verbose     isWorkspace: false,
npm verbose     dependents: [ [Object] ]
npm verbose   }
npm verbose } TypeError: Cannot read properties of undefined (reading 'extraneous')
npm verbose     at printNode (/opt/homebrew/lib/node_modules/npm/lib/utils/explain-dep.js:24:13)
npm verbose     at explainNode (/opt/homebrew/lib/node_modules/npm/lib/utils/explain-dep.js:4:3)
npm verbose     at explain (/opt/homebrew/lib/node_modules/npm/lib/utils/explain-eresolve.js:39:16)
npm verbose     at #tryWriteLog (/opt/homebrew/lib/node_modules/npm/lib/utils/display.js:394:41)
npm verbose     at /opt/homebrew/lib/node_modules/npm/lib/utils/display.js:286:28
npm verbose     at process.<anonymous> (/opt/homebrew/lib/node_modules/npm/lib/utils/display.js:148:10)
npm verbose     at process.emit (node:events:532:35)
npm verbose     at Object.warn (/opt/homebrew/lib/node_modules/npm/node_modules/proc-log/lib/index.js:62:22)
npm verbose     at PlaceDep.warnPeerConflict (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:496:9)
npm verbose     at new PlaceDep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:165:14)```


and when I install framer-motion I get this:

```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @monogrid/gainmap-js@3.0.5
npm warn Found: three@0.154.0
npm warn node_modules/three
npm warn   peer three@">=0.126" from @react-spring/three@9.7.4
npm warn   node_modules/@react-spring/three
npm warn     peer @react-spring/three@"*" from shadergradient@1.2.14
npm warn     node_modules/shadergradient
npm warn   11 more (@react-three/drei, @react-spring/three, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer three@">= 0.159.0" from @monogrid/gainmap-js@3.0.5
npm warn node_modules/@react-three/drei/node_modules/@monogrid/gainmap-js
npm warn   @monogrid/gainmap-js@"^3.0.5" from @react-three/drei@9.109.5
npm warn   node_modules/@react-three/drei
npm warn
npm warn Conflicting peer dependency: three@0.167.1
npm warn node_modules/three
npm warn   peer three@">= 0.159.0" from @monogrid/gainmap-js@3.0.5
npm warn   node_modules/@react-three/drei/node_modules/@monogrid/gainmap-js
npm warn     @monogrid/gainmap-js@"^3.0.5" from @react-three/drei@9.109.5
npm warn     node_modules/@react-three/drei
```

This affects my VSCode IntelliSense and results in VSCode not giving me suggests props (mega annoying for devs). Does anyone have a fix for this? Thanks!

**Comment by minorole** [comment]
I fixed similar problem with:

1. package.json set related dependency to latest
2. then remove the existing installed files like package lock etc
3. run npm cache clean --force && npm install

**Comment by AthenaKam** [comment]
> I fixed similar problem with:
> 
> 1. package.json set related dependency to latest
> 2. then remove the existing installed files like package lock etc
> 3. run npm cache clean --force && npm install

The related dependency isn't something you install directly installed by me, it is installed as part of shadergradient itself as a sub dependency. When i try to install the latest version of three i get the following error:

```npm warn ERESOLVE overriding peer dependency
npm warn While resolving: aaam-bot-client@0.5.1
npm warn Found: three@0.154.0
npm warn node_modules/three
npm warn   peer three@">=0.126" from @react-spring/three@9.7.4
npm warn   node_modules/@react-spring/three
npm warn     peer @react-spring/three@"*" from shadergradient@1.2.14
npm warn     node_modules/shadergradient
npm warn   12 more (@react-three/drei, @react-spring/three, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer three@"0.154.0" from shadergradient@1.2.14
npm warn node_modules/shadergradient
npm warn   shadergradient@"^1.2.14" from the root project```

**Comment by ARbayung** [comment]
I have the same problem. When im developing locally an running on VS everything seems to work fine, but when I try to deploy the project in vercel the packages conflict and fails deployment.

**Comment by AbduHany** [comment]
Did anyone find a solution to this?

**Comment by tomShoutTheSecond** [comment]
I have the same problem in my React Vite TS app, could not resolve dependencies

```
npm i @react-three/fiber
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: 
npm error Found: react@19.1.1
npm error node_modules/react
npm error   peer react@">=16.8.0" from @emotion/react@11.14.0
npm error   node_modules/@emotion/react
npm error     peer @emotion/react@"^11.0.0-rc.0" from @emotion/styled@11.14.1
npm error     node_modules/@emotion/styled
npm error       peerOptional @emotion/styled@"^11.3.0" from @mui/material@7.3.4
npm error       node_modules/@mui/material
npm error         @mui/material@"^7.3.2" from the root project
npm error       3 more (@mui/styled-engine, @mui/system, the root project)
npm error     peerOptional @emotion/react@"^11.5.0" from @mui/material@7.3.4
npm error     node_modules/@mui/material
npm error       @mui/material@"^7.3.2" from the root project
npm error     2 more (@mui/styled-engine, @mui/system)
npm error   peer react@">=16.8.0" from @emotion/styled@11.14.1
npm error   node_modules/@emotion/styled
npm error     peerOptional @emotion/styled@"^11.3.0" from @mui/material@7.3.4
npm error     node_modules/@mui/material
npm error       @mui/material@"^7.3.2" from the root project
npm error     peerOptional @emotion/styled@"^11.3.0" from @mui/styled-engine@7.3.3
npm error     node_modules/@mui/styled-engine
npm error       @mui/styled-engine@"^7.3.3" from @mui/system@7.3.3
npm error       node_modules/@mui/system
npm error         @mui/system@"^7.3.3" from @mui/material@7.3.4
npm error         node_modules/@mui/material
npm error     2 more (@mui/system, the root project)
npm error   15 more (@emotion/use-insertion-effect-with-fallbacks, ...)
npm error
npm error Could not resolve dependency:
npm error @react-three/fiber@"*" from the root project
npm error
npm error Conflicting peer dependency: react@19.2.3
npm error node_modules/react
npm error   peer react@"^19.2.3" from react-dom@19.2.3
npm error   node_modules/react-dom
npm error     react-dom@"^19.1.1" from the root project
npm error     peerOptional react-dom@">=19 <19.3" from @react-three/fiber@9.5.0
npm error     node_modules/@react-three/fiber
npm error       @react-three/fiber@"*" from the root project
npm error     3 more (@expo/metro-runtime, expo-gl, react-native-web)
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
...
```
